name: close-issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.issue.body }}
          regex: '[Vv]ersion.*:.*202\d.\d\d?.\d\d?'
      - if: ${{ steps.regex-match.outputs.match != '' }}
        name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          close-reason: not_planned
          comment: |
            It seems like you're using an old version of Bottles. Please upgrade to the latest version, and try to reproduce the bug.
